spring:
  application:
    name: main-backend

  datasource:
    url: jdbc:mysql://localhost:3306/pipeline
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

etl:
  file-monitor:
    input-directory: data/input
    processed-directory: data/processed
    failed-directory: data/failed
    enabled: true
